Repository pi-hole/FTL, pull requests merged in 2018-04, with the labels that each got.

#247 FTLDNS: Measure and store response time for queries
  FTL.h
  api.c
  dnsmasq_interface.c
Labels: Enhancement

#241 align this readme with the core one. formatting and layout is now th…
  README.md
Labels: Documentation

#251 Several FTLDNS improvements
  FTL.h
  api.c
  database.c
  datastructure.c
  dnsmasq/cache.c
  dnsmasq/forward.c
  dnsmasq/rfc1035.c
  dnsmasq_interface.c
  dnsmasq_interface.h
  gc.c
Labels: Enhancement, FTLDNS

#253 Internal name resolving functionality
  FTL.h
  Makefile
  api.c
  database.c
  datastructure.c
  gc.c
  resolve.c
  routines.h
  setupVars.c
Labels: Enhancement, FTLDNS

#254 Add IGNORE_LOCALHOST config option
  FTL.h
  README.md
  config.c
  database.c
  dnsmasq_interface.c
Labels: Enhancement, FTLDNS

#259 Simple list format for gravity.list and black.list
  FTL.h
  README.md
  config.c
  dnsmasq/cache.c
  dnsmasq/rfc1035.c
  dnsmasq_interface.c
  dnsmasq_interface.h
  grep.c
  memory.c
Labels: Enhancement, FTLDNS

#261 Merge simple domain format into FTLDNS beta branch
  FTL.h
  README.md
  config.c
  dnsmasq/cache.c
  dnsmasq/rfc1035.c
  dnsmasq_interface.c
  dnsmasq_interface.h
  grep.c
  memory.c
Labels: FTLDNS

#265 General FTLDNS optimizations
  database.c
  datastructure.c
  dnsmasq_interface.c
  signals.c
Labels: Enhancement, FTLDNS

#264 Add "blocked" as another "forward destination"
  api.c
Labels: Enhancement, FTLDNS

#268 Fix IPv6 blocking and blocking reason detection
  dnsmasq/rfc1035.c
  dnsmasq_interface.c
Labels: Bugfix, FTLDNS

#270 Silence wrong FATAL ERROR messages
  datastructure.c
Labels: Bugfix, FTLDNS
