Repository pi-hole/FTL, pull requests merged in 2018-11, with the labels that each got.

#411 Properly account for user-defined wildcards
  dnsmasq_interface.c
Labels: Bugfix

#412 Merge bugfix #411 also into dnsmasq/v2.80
  dnsmasq_interface.c
Labels: Code maintanance

#413 Fix record_source() sometimes incorrectly returning regex.list
  dnsmasq/dnsmasq.h
Labels: Bugfix

#417 Fix/privacy levels regex filtering
  FTL.h
  api.c
  config.c
  database.c
  datastructure.c
  dnsmasq/cache.c
  dnsmasq/dnsmasq.h
  dnsmasq/option.c
  dnsmasq_interface.c
  dnsmasq_interface.h
  routines.h
Labels: Bugfix

#416 Adjustable file locations
  FTL.h
  args.c
  config.c
  log.c
  memory.c
  routines.h
  test/run.sh
Labels: Code maintanance, Enhancement

#401 Upgrade embedded dnsmasq to v2.80
  FTL.h
  Makefile
  api.c
  args.c
  config.c
  database.c
  datastructure.c
  dnsmasq/auth.c
  dnsmasq/bpf.c
  dnsmasq/cache.c
  dnsmasq/config.h
  dnsmasq/dbus.c
  dnsmasq/dhcp-common.c
  dnsmasq/dhcp-protocol.h
  dnsmasq/dhcp.c
  dnsmasq/dhcp6.c
  dnsmasq/dns-protocol.h
  dnsmasq/dnsmasq.c
  dnsmasq/dnsmasq.h
  dnsmasq/dnssec.c
  dnsmasq/dump.c
  dnsmasq/forward.c
  dnsmasq/lease.c
  dnsmasq/log.c
  dnsmasq/metrics.c
  dnsmasq/metrics.h
  dnsmasq/netlink.c
  dnsmasq/network.c
  dnsmasq/option.c
  dnsmasq/rfc1035.c
  dnsmasq/rfc2131.c
  dnsmasq/rfc3315.c
  dnsmasq/slaac.c
  dnsmasq/tftp.c
  dnsmasq/ubus.c
  dnsmasq/util.c
  dnsmasq_interface.c
  dnsmasq_interface.h
  gc.c
  log.c
  memory.c
  routines.h
  test/run.sh
Labels: Enhancement

#421 Revert blacklist file path to the original
  config.c
Labels: Code maintanance

#422 Simplify upstream percentage computation
  api.c
Labels: Code maintanance

#423 Fix query status if forwarded query was partially replied to from cache
  dnsmasq_interface.c
Labels: Bugfix
