Repository pi-hole/FTL, pull requests merged in 2018-09, with the labels that each got.

#371 Add guarding {} around if statement
  dnsmasq/rfc1035.c
Labels: Bugfix

#373 Don't forget to reset "new" flag on client struct when name is resolved
  resolve.c
Labels: Bugfix

#374 Don't count locally blocked queries as externally blocked
  dnsmasq_interface.c
Labels: Bugfix

#375 Ignore dnsmasq compiled files
  .gitignore
Labels: Code maintanance

#376 Remove privacy.c
  privacy.c
Labels: Bugfix, Code maintanance

#380 Fix exit message showing invalid program run time
  main.c
Labels: Bugfix

#388 Fix behavior when no whitelist file is present
  regex.c
Labels: Bugfix
