Repository pi-hole/FTL, pull requests merged in 2018-08, with the labels that each got.

#333 Run DB cleaning once GC is finished
  gc.c
Labels: Bugfix

#337 Fix incorrect log_regex_error() subroutine
  regex.c
Labels: Bugfix

#348 Add user-defined wildcard blocking support
  dnsmasq_interface.c
Labels: Enhancement

#350 Show "regex.list" as source of regex blocked queries
  dnsmasq/cache.c
  dnsmasq/dnsmasq.h
  dnsmasq_interface.c
Labels: Enhancement

#349 Analyze/show more query types
  FTL.h
  api.c
  config.c
  database.c
  dnsmasq/rfc1035.c
  dnsmasq_interface.c
  gc.c
Labels: Enhancement, FTLDNS

#352 Add possibility to request all queries for specific query types or forward destinations
  api.c
Labels: Enhancement

#354 Fix missing branch tag build
  .circleci/config.yml
Labels: Bugfix

#355 Detect externally blocked based on returned IP address (e.g., for OpenDNS)
  dnsmasq_interface.c
Labels: Enhancement

#357 Add PRIVACY_NOSTATS mode that skips all analysis
  FTL.h
  config.c
  database.c
  dnsmasq_interface.c
Labels: Enhancement

#358 Add DBIMPORT config boolean
  FTL.h
  config.c
  main.c
Labels: Enhancement

#362 Outsource query ID determination
  dnsmasq_interface.c
Labels: Code maintanance

#366 Ensure proper file ownerships if pihole-FTL is started as root
  dnsmasq/dnsmasq.c
  dnsmasq_interface.c
  dnsmasq_interface.h
Labels: Bugfix, Enhancement

#368 Fix usage of wrong variable in query_externally_blocked()
  dnsmasq_interface.c
Labels: Bugfix

#351 Determine blocking status enabled/disabled by reading setupVars.conf
  grep.c
Labels: Enhancement

#369 Apply patch: Fix crash parsing a --synth-domain with no prefix.
  dnsmasq/option.c
Labels: Bugfix, dnsmasq bug
