Repository pi-hole/FTL, pull requests merged in 2018-02, with the labels that each got.

#225 Bugfix for API_QUERY_LOG_SHOW option
  api.c
Labels: Bugfix

#226 Fix accidentally trying to free NULL
  flush.c
Labels: Bugfix

#227 Define our own strdup()
  memory.c
Labels: Bugfix, Enhancement

#235 Test for wildcarddomains == NULL in flush.c
  flush.c
  test/test_suite.sh
Labels: Enhancement
