Repository pi-hole/FTL, pull requests merged in 2018-07, with the labels that each got.

#320 Skip empty regex.list lines
  regex.c
Labels: Enhancement, FTLDNS

#327 Don't use regex filters if blocking is disabled
  FTL.h
  dnsmasq_interface.c
  grep.c
Labels: Bugfix

#326 RegEx debugging mode
  FTL.h
  config.c
  dnsmasq_interface.c
  regex.c
Labels: Enhancement

#329 Fix Segfault during getallqueries-client
  api.c
Labels: Bugfix
