Repository pi-hole/FTL, pull requests merged in 2018-12, with the labels that each got.

#419 Half memory usage of NULL blocking mode
  dnsmasq_interface.c
Labels: Enhancement

#429 Use shared memory objects for data
  FTL.h
  Makefile
  api.c
  database.c
  datastructure.c
  dnsmasq_interface.c
  gc.c
  log.c
  main.c
  memory.c
  regex.c
  request.c
  resolve.c
  routines.h
  shmem.c
  shmem.h
  socket.c
  threads.c
Labels: API

#430 Fix no-daemon mode forking dnsmasq and not logging
  args.c
  dnsmasq_interface.c
  log.c
Labels: Bugfix

#433 Add new NODATA blocking mode
  FTL.h
  config.c
  dnsmasq_interface.c
Labels: FTLDNS

#431 Update config.c
  config.c
Labels: Bugfix

#439 Zero initialize all_addr structs
  dnsmasq_interface.c
Labels: Bugfix, Code maintanance

#435 Pi-hole FTL v4.1.1
  args.c
  config.c
  dnsmasq/forward.c
  dnsmasq_interface.c
  dnsmasq_interface.h
  gc.c
  log.c
Labels: Release

#445 Fix segfault in FTL_reply corresponding to name being null
  dnsmasq_interface.c
Labels: Release

#443 Merge hotfix v4.1.1 and v4.1.2 into dev
  dnsmasq/forward.c
  dnsmasq_interface.c
  dnsmasq_interface.h
Labels: Release

#449 Fix: Deadlock situation in resolving subroutines
  request.c
  resolve.c
  shmem.c
  shmem.h
  socket.c
Labels: Bugfix, Code maintanance
