Repository pi-hole/FTL, pull requests merged in 2019-07, with the labels that each got.

#604 Change SQLITE_TRANSIENT to SQLITE_STATIC
  database.c
Labels: Enhancement

#591 Add IPv6 support for network table
  Makefile
  database.c
  networktable.c
  routines.h
  test/test_suite.bats
Labels: Discourse Feature Request, Enhancement

#602 Implement changes due to core/#2803
  test/gravity.db.sql
Labels: Code maintanance, Tests

#598 Tests: Dependence on shared libraries and a specific interpreter
  test/run.sh
  test/test_suite.bats
Labels: Tests

#610 Database error checking
  src/database/common.c
  src/database/common.h
  src/database/network-table.c
  src/database/query-table.c
  src/main.c
Labels: Bugfix, Enhancement

#613 Improve debug flag handling in config file
  src/config.c
Labels: Enhancement

#618 Print content of /dev/shm in crash report
  src/api/api.c
  src/files.c
  src/files.h
  src/log.c
  src/log.h
  src/signals.c
Labels: Enhancement

#619 Print architecture FTL was compiled for
  Makefile
  src/log.c
  test/test_suite.bats
Labels: Enhancement

#620 Add new config flag REGEX_IGNORECASE
  src/config.c
  src/config.h
  src/regex.c
Labels: Enhancement

#623 Fix failure during parse_neighbor_cache not unlocking shared memory
  src/database/common.c
  src/database/common.h
  src/database/network-table.c
  src/database/query-table.c
Labels: Bug in development, Bugfix
