Repository pi-hole/FTL, pull requests merged in 2019-02, with the labels that each got.

#488 Use improved "externally blocked" criterion
  dnsmasq_interface.c
Labels: Bugfix

#495 Re-add source record passing to subroutines
  dnsmasq/rfc1035.c
Labels: Bugfix

#497 Pi-hole FTL v4.2.1
  dnsmasq/config.h
  dnsmasq/rfc1035.c
  log.c
  main.c
  routines.h
  signals.c
Labels: Release

#503 Remove dnsmasq_interface_actions.c
  dnsmasq_interface_actions.c
Labels: Code maintanance

#505 Fix incorrect fatal error message in findQueryID
  dnsmasq_interface.c
Labels: Bugfix

#512 Add DEBUG_ALL config option
  config.c
Labels: Enhancement

#513 Fix last timestamp getting set to zero if no queries were saved
  database.c
Labels: Bugfix

#510 Pi-hole FTL v4.2.2
  FTL.h
  Makefile
  api.c
  config.c
  daemon.c
  database.c
  datastructure.c
  dnsmasq_interface.c
  gc.c
  log.c
  main.c
  memory.c
  overTime.c
  routines.h
  shmem.c
  shmem.h
  signals.c
Labels: Release

#515 Merge v4.2.2 changes into development
  FTL.h
  Makefile
  api.c
  config.c
  daemon.c
  database.c
  datastructure.c
  dnsmasq_interface.c
  gc.c
  log.c
  main.c
  memory.c
  overTime.c
  routines.h
  shmem.c
  signals.c
Labels: Code maintanance

#517 Return successful exit code instead of failure
  main.c
Labels: Bugfix

#519 Pi-hole FTL v4.2.3
  FTL.h
  shmem.c
  shmem.h
Labels: Bugfix, Release

#523 Merge hotfix changes into development
  FTL.h
  shmem.c
  shmem.h
Labels: Code maintanance
