Repository pi-hole/FTL, pull requests merged in 2019-01, with the labels that each got.

#451 Show file:line in hook calls (debug mode only)
  Makefile
  dnsmasq_interface.c
  dnsmasq_interface.h
Labels: Code maintanance

#452 Bugfix for new, more efficient NULL blocking mode
  dnsmasq_interface.c
Labels: Bugfix

#454 SHM tweaks
  shmem.c
Labels: Code maintanance, Enhancement

#453 Add check for required Linux capabilities
  .circleci/config.yml
  Makefile
  capabilities.c
  docker/aarch64/Dockerfile
  docker/arm/Dockerfile
  docker/armhf/Dockerfile
  docker/x86_32/Dockerfile
  docker/x86_64/Dockerfile
  main.c
  routines.h
Labels: Bugfix

#456 Gravity domains should not have REVERSE set
  dnsmasq_interface.c
Labels: Bugfix

#455 Process ARP data for new network table
  .gitignore
  FTL.h
  Makefile
  aux/macvendor.py
  config.c
  database.c
  datastructure.c
  dnsmasq_interface.c
  gc.c
  memory.c
  networktable.c
  request.c
  routines.h
Labels: Enhancement

#463 Always allocate also empty strings in getMACVendor()
  networktable.c
Labels: Bugfix

#466 Fine grained debug message filtering
  FTL.h
  args.c
  config.c
  database.c
  dnsmasq_interface.c
  gc.c
  grep.c
  log.c
  networktable.c
  regex.c
  routines.h
  shmem.c
  socket.c
Labels: Enhancement

#469 Trim any whitespace characters around config keys
  config.c
  routines.h
  setupVars.c
Labels: Enhancement

#470 findQueryID(): Ensure indices are non-negative
  dnsmasq_interface.c
Labels: Bugfix

#474 Micro optimizations for adding blocking domains
  dnsmasq_interface.c
Labels: Code maintanance

#473 Update development from release/v4.2
  database.c
  dnsmasq_interface.c
  docker/arm/Dockerfile
Labels: Code maintanance

#476 Explicitly use clientID for newOverTimeClient()
  datastructure.c
  routines.h
  shmem.c
Labels: Bugfix, Code maintanance

#478 Fix crash in destroy_shmem()
  shmem.c
Labels: Bugfix

#480 Fix dnsmasq v2.80 implementation
  dnsmasq/dhcp6.c
  dnsmasq/inotify.c
  dnsmasq/network.c
  dnsmasq/rfc1035.c
  dnsmasq/util.c
Labels: Bugfix

#482 Update development from release/v4.2
  datastructure.c
  dnsmasq/dhcp6.c
  dnsmasq/inotify.c
  dnsmasq/network.c
  dnsmasq/rfc1035.c
  dnsmasq/util.c
  routines.h
  shmem.c
Labels: Bugfix, Code maintanance

#479 Add arm-rpi build
  docker/arm/Dockerfile
Labels: Bugfix, ON HOLD

#483 Fix counters->clients getting incremented twice due to v4.2 merge
  datastructure.c
Labels: Bug in development, Bugfix
