Repository pi-hole/FTL, pull requests merged in 2019-05, with the labels that each got.

#568 Fix string reference held across locks
  resolve.c
  shmem.h
Labels: Bugfix

#572 Use memcpy instead of strncpy where advised
  api.c
  args.c
  shmem.c
Labels: Code maintanance

#574 Do not print errors when we create the database for the first time
  database.c
Labels: Enhancement

#573 Prevent possible memory corruption in addstr()
  shmem.c
Labels: Bugfix

#570 Hotfix v4.3.1
  networktable.c
  resolve.c
Labels: Release

#577 Identify clients by hardware address not hardware + IP address
  database.c
  networktable.c
Labels: Bugfix
