Repository pi-hole/FTL, pull requests merged in 2019-06, with the labels that each got.

#580 Add support for DESTDIR
  Makefile
Labels: Enhancement

#581 Improve Alpine support
  Makefile
Labels: Bugfix

#584 Fix regex not blocking in some cases
  regex.c
Labels: Bugfix

#588 Tests: Run as user pihole
  test/run.sh
  test/test_suite.bats
Labels: Tests

#589 Tests: Test against WARNING and ERROR messages
  test/run.sh
  test/test_suite.bats
Labels: Tests

#587 Explicitly set permissions of database file after creation
  Makefile
  database.c
  files.c
  routines.h
  test/run.sh
  test/test_suite.bats
Labels: Bugfix

#553 Improve musl support + run tests on musl and 32bit binaries
  .circleci/config.yml
  Makefile
  dnsmasq/dnsmasq.h
  docker/x86_32/Dockerfile
  docker/x86_64-musl/Dockerfile
  docker/x86_64/Dockerfile
  signals.c
  test/run.sh
  test/test_suite.bats
Labels: Enhancement

#594 Generate self-contained musl binary
  .circleci/config.yml
  Makefile
  docker/x86_64-musl/Dockerfile
Labels: Enhancement

#595 Unify version determination mechanism
  Makefile
  api.c
  args.c
  dnsmasq/option.c
  log.c
  routines.h
Labels: Bugfix

#597 Tests: Do not hard-code IP address of client expected during tests
  test/test_suite.bats
Labels: Bugfix, Tests

#601 Move ./aux/macvendor.py -> ./macvendor.py
  .gitignore
  macvendor/macvendor.py
Labels: Code maintanance

#600 Use whitelist table in gravity.db directly
  dnsmasq_interface.c
  gravity.c
  main.c
  regex.c
  request.c
  routines.h
Labels: Enhancement
