Repository pi-hole/FTL, pull requests merged in 2020-06, with the labels that each got.

#769 Process cached SRV records
  src/dnsmasq/rfc1035.c
Labels: Bugfix

#784 Add NAMES_FROM_NETDB option
  src/config.c
  src/config.h
  src/resolve.c
Labels: Discourse Feature Request

#792 Fix broken RESOLVE_IPV{4,6} setting
  src/database/network-table.c
  src/resolve.c
Labels: Bugfix

#787 Store client group information in shared memory
  src/database/gravity-db.c
  src/datastructure.c
  src/datastructure.h
Labels: Bug in development, Bugfix

#796 Allow no/false and yes/true for all config options.
  src/config.c
Labels: Enhancement

#797 Reacquire client and upstream pointers after a name resolution
  src/resolve.c
Labels: Bugfix

#798 Be less nice
  src/capabilities.c
  src/config.c
  test/test_suite.bats
Labels: Enhancement

#780 Add warning for invalid hostnames to FTL message table
  src/database/common.c
  src/database/common.h
  src/database/message-table.c
  src/database/message-table.h
  src/resolve.c
Labels: Enhancement

#793 Fix for #790
  src/dnsmasq_interface.c
Labels: Bugfix

#813 [dnsmasq] Fix a possible buffer overflow when handling TCP requests
  src/dnsmasq/dnsmasq.c
Labels: Bugfix, dnsmasq bug

#811 Improve signal handling
  src/dnsmasq/helper.c
  src/dnsmasq_interface.c
  src/main.c
  src/signals.c
  src/signals.h
Labels: Bugfix, Enhancement

#818 Terminate main process when a fork fails
  src/main.c
  src/signals.c
Labels: Bugfix

#819 Add support for additional query types
  src/FTL.h
  src/api/api.c
  src/datastructure.h
  src/dnsmasq/forward.c
  src/dnsmasq_interface.c
  src/dnsmasq_interface.h
  src/overTime.h
  src/shmem.h
  test/test_suite.bats
Labels: Enhancement

#822 Fix dnsmasq TCP worker buffer overflow
  src/dnsmasq/dnsmasq.c
Labels: Bugfix, dnsmasq bug
