Repository pi-hole/FTL, pull requests merged in 2021-02, with the labels that each got.

#1055 Improvements for `dhcp-discover`
  src/dhcp-discover.c
  src/dnsmasq/option.c
Labels: Bugfix, PR: Approved

#1054 Prevent crashing when FTL is started multiple times
  src/CMakeLists.txt
  src/gc.c
  src/log.c
  src/log.h
  src/main.c
  src/procps.c
  src/procps.h
  src/shmem.c
  test/test_suite.bats
Labels: Enhancement, PR: Approved, SECURITY

#1053 Add output of how much memory in /dev/shm is used by FTL itself
  src/shmem.c
Labels: Debugging, PR: Approved

#1057 Fix inconsistent counters on CNAME or exernally blocked queries
  src/database/query-table.c
  src/datastructure.c
  src/datastructure.h
  src/dnsmasq_interface.c
Labels: Bugfix, PR: Approval Required

#1052 Add per-client rate-limiting
  src/config.c
  src/config.h
  src/database/query-table.c
  src/datastructure.h
  src/dnsmasq_interface.c
  src/gc.c
Labels: Enhancement, PR: Approval Required, SECURITY

#1058 Retain pseudoheader in blocked queries
  src/dnsmasq/forward.c
Labels: Bug, Bugfix in progress

#1059 Pi-hole FTL v5.7
  src/CMakeLists.txt
  src/config.c
  src/config.h
  src/database/query-table.c
  src/datastructure.c
  src/datastructure.h
  src/dhcp-discover.c
  src/dnsmasq/forward.c
  src/dnsmasq/option.c
  src/dnsmasq_interface.c
  src/gc.c
  src/log.c
  src/log.h
  src/main.c
  src/procps.c
  src/procps.h
  src/shmem.c
  test/test_suite.bats
Labels: Release

#1069 Change to refreshed logo.
  README.md
Labels: PR: Approval Required

#1067 Fix for `pihole-FTL test`
  src/api/socket.c
  src/args.c
  src/daemon.c
  src/daemon.h
  src/database/database-thread.c
  src/database/message-table.c
  src/database/query-table.c
  src/database/query-table.h
  src/dnsmasq/dnsmasq.c
  src/dnsmasq_interface.c
  src/gc.c
  src/log.c
  src/main.c
  src/procps.c
  src/procps.h
  src/resolve.c
  src/shmem.c
  src/shmem.h
  src/signals.c
  src/syscalls/vsnprintf.c
  test/test_suite.bats
Labels: Bugfix, PR: Approved

#1061 Fix incorrect "FATAL: Trying to access upstream ID -1" warning in the logs
  src/database/query-table.c
  src/dnsmasq_interface.c
  src/shmem.c
Labels: Bugfix, PR: Approved
