Repository pi-hole/FTL, pull requests merged in 2022-06, with the labels that each got.

#1354 New API endpoint ">gateway"
  src/api/api.c
  src/api/api.h
  src/api/request.c
  test/test_suite.bats
Labels: API, Documentation needed

#1349 DELAY_STARTUP only when booting
  src/FTL.h
  src/daemon.c
Labels: Enhancement, Documentation needed

#1355 Add interface info for PADD
  src/api/api.c
  src/api/api.h
  src/api/request.c
  src/log.c
  test/test_suite.bats
Labels: Documentation needed

#1359 Stale exempt
  .github/workflows/stale.yml
Labels: internal

#1356 Upgrade stale action to v5
  .github/workflows/stale.yml
Labels: internal

#1361 Add dependabot for github-actions
  .github/dependabot.yml
Labels: internal

#1357 Add stale-issue-reason: not-planned
  .github/workflows/stale.yml
Labels: internal

#1370 Improve telnet error handling
  src/api/api.c
  src/api/request.c
  src/api/socket.c
Labels: Bugfix, Bug in development
