Repository pi-hole/FTL, pull requests merged in 2022-08, with the labels that each got.

#1396 Major rewrite of the socket processing routines
  src/api/api.c
  src/api/api.h
  src/api/request.c
  src/api/request.h
  src/api/socket.c
  src/api/socket.h
  src/daemon.c
  src/daemon.h
  src/dnsmasq_interface.c
  src/dnsmasq_interface.h
  src/enums.h
  src/syscalls/accept.c
  src/syscalls/calloc.c
  src/syscalls/fopen.c
  src/syscalls/ftlallocate.c
  src/syscalls/pthread_mutex_lock.c
  src/syscalls/realloc.c
  src/syscalls/recv.c
  src/syscalls/recvfrom.c
  src/syscalls/select.c
  src/syscalls/sendto.c
  src/syscalls/vasprintf.c
  src/syscalls/vfprintf.c
  src/syscalls/vsnprintf.c
  src/syscalls/vsprintf.c
  src/syscalls/write.c
Labels: Bugfix, API, PR: Approval Required

#1395 Update ftl-build containers
  .github/workflows/build.yml
  test/arch_test.sh
  test/pdns/pdns.conf
  test/pdns/recursor.conf
  test/pdns/setup.sh
  test/test_suite.bats
Labels: Breaking change, PR: Approval Required, internal

#1403 [skip ci] a couple of spelling changes
  src/api/api.c
  src/database/common.h
Labels: internal

#1408 Don't enforce API sockets
  src/api/socket.c
Labels: Bugfix

#1410 Fix storing of API thread IDs
  src/api/socket.c
  src/daemon.c
  src/daemon.h
Labels: Bugfix

#1388 Tweak build and deploy process
  .github/workflows/build.yml
  deploy.sh
Labels: PR: Code Review Required, internal

#1412 Ensure compatibility with gcc 11.2.0 (Ubuntu 11.2.0-19ubuntu1)
  src/syscalls/fopen.c
  src/syscalls/syscalls.h
Labels: Code maintanance

#1413 Substitute "." for empty domain names
  src/dnsmasq_interface.c
  src/dnsmasq_interface.h
Labels: Discourse Feature Request
