Repository pi-hole/FTL, pull requests merged in 2022-12, with the labels that each got.

#1498 Fix incorrect DNSSEC-related warning during history import
  src/database/query-table.c
Labels: Bugfix

#1502 Exit immediately after running dnsmasq-test
  src/args.c
Labels: Bugfix

#1501 Improve -vv and --help
  src/args.c
  src/dnsmasq/dnsmasq.c
  test/test_suite.bats
Labels: Enhancement

#1510 Update embedded dnsmasq to v2.88
  CMakeLists.txt
  src/dnsmasq/dhcp-common.c
Labels: dnsmasq update

#1504 Add merge conflict workflow
  .github/workflows/merge-conflict.yml
Labels: PR: Approval Required

#1514 Always store time we start saving to the database
  src/database/query-table.c
Labels: Bugfix

#1506 Use github cli to sync master back to development
  .github/workflows/sync-back-to-dev.yml
Labels: PR: Approval Required, internal
