Repository pi-hole/FTL, pull requests merged in 2022-01, with the labels that each got.

#1270 Improve Linux capabilities check
  src/capabilities.c
  src/main.c
Labels: Enhancement

#1273 Update embedded dnsmasq
  CMakeLists.txt
  src/dnsmasq/cache.c
  src/dnsmasq/dhcp-common.c
  src/dnsmasq/dhcp.c
  src/dnsmasq/dhcp6-protocol.h
  src/dnsmasq/dhcp6.c
  src/dnsmasq/dnsmasq.c
  src/dnsmasq/dnsmasq.h
  src/dnsmasq/domain-match.c
  src/dnsmasq/edns0.c
  src/dnsmasq/forward.c
  src/dnsmasq/helper.c
  src/dnsmasq/network.c
  src/dnsmasq/option.c
  src/dnsmasq/pattern.c
  src/dnsmasq/rfc3315.c
  src/dnsmasq/tftp.c
Labels: dnsmasq update

#1279 [Maintenance] Sync Master back to Dev when code is pushed to master
  .github/release.yml
  .github/workflows/sync-back-to-dev.yml
Labels: internal

#1282 Enable history and auto-completion for embedded SQLite3 engine
  src/CMakeLists.txt
Labels: Discourse Feature Request

#1255 Optimize queries table
  src/database/common.c
  src/database/gravity-db.c
  src/database/query-table.c
  src/database/query-table.h
  src/enums.h
  test/test_suite.bats
Labels: Enhancement, Documentation needed

#1283 Use embedded SQLite3 engine for the tests
  test/gravity.db.sql
  test/pdns/setup.sh
  test/run.sh
  test/test_suite.bats
Labels: Tests

#1284 Add others section to upstream servers pie chart
  src/api/api.c
  test/test_suite.bats
Labels: Enhancement

#1287 Print more details in CLI regex-test
  src/datastructure.c
  src/regex.c
  test/test_suite.bats
Labels: Enhancement

#1289 Tidy Up CI scripts - untangle from variables named after CircleCI
  .circleci/build-CI.sh
  .circleci/config.yml
  .github/workflows/build.yml
  build.sh
  src/gen_version.cmake
  test/arch_test.sh
  test/run.sh
  test/test_suite.bats
Labels: internal
