Repository pi-hole/FTL, pull requests merged in 2022-07, with the labels that each got.

#1367 Do not run built workflow on dependabot pushes and PRs
  .github/workflows/build.yml
Labels: internal

#1373 Use cmake --install . instead of make install
  build.sh
Labels: Enhancement, Code maintanance

#1374 Run stale workflow at 8:00 once per day
  .github/workflows/stale.yml
Labels: PR: Approval Required

#1375 Change default log file path to /var/log/pihole/FTL.log
  src/config.c
  src/database/common.c
  src/database/gravity-db.c
  src/database/message-table.c
  test/run.sh
  test/test_suite.bats
Labels: Changes default behavior

#1376 Fix close-issue-reason
  .github/workflows/stale.yml
Labels: PR: Approval Required

#1383 Fix status of blocked special domains when they are in FTL's DNS cache
  src/dnsmasq_interface.c
Labels: Bugfix

#1384 Revert "Remove PID and PORT file during shutdown"
  src/api/socket.c
  src/daemon.c
Labels: Bugfix

#1386 Increase DELAY_UPTIME to 180 seconds
  src/FTL.h
Labels: Discourse Feature Request, Documentation needed

#1391 Update build.yml to use latest FTL build containers
  .github/workflows/build.yml
Labels: internal

#1390 Explicit set minor and patch version on used actions
  .github/workflows/build.yml
  .github/workflows/codespell.yml
  .github/workflows/stale.yml
  .github/workflows/sync-back-to-dev.yml
Labels: PR: Approval Required, internal
