Repository pi-hole/FTL, pull requests merged in 2022-05, with the labels that each got.

#1345 Always return full overTime data
  src/FTL.h
  src/api/api.c
  src/dnsmasq_interface.c
  src/gc.c
  src/overTime.c
Labels: Bugfix

#1352 Fix outdated link to Wireshark manufacturer database
  tools/macvendor.py
Labels: Bugfix

#1353 Fix forward percentages with all-servers
  src/api/api.c
Labels: Bugfix

#1341 Make REPLY_WHEN_BUSY=DROP the new default (was ALLOW)
  src/config.c
Labels: Discussion, Bugfix

#1346 Change default log facility to /var/log/pihole/pihole-FTL.log
  src/config.c
  test/dnsmasq.conf
  test/run.sh
  test/test_suite.bats
Labels: PR: Approved, Changes default behavior
