Repository pi-hole/FTL, pull requests merged in 2022-04, with the labels that each got.

#1322 Fix query counts
  src/api/api.c
  src/database/query-table.c
  src/dnsmasq_interface.c
  test/test_suite.bats
Labels: Bugfix

#1326 Add stale bot to FTL repo
  .github/workflows/stale.yml
Labels: internal

#1327 Fix overtime computation logic broken in PR #1312
  src/overTime.c
Labels: Bugfix, Bug in development

#1337 Add code-spell action
  .codespellignore
  .github/workflows/codespell.yml
  src/FTL.h
  src/api/api.c
  src/daemon.c
  src/database/gravity-db.c
  src/database/network-table.c
  src/database/query-table.c
  src/datastructure.c
  src/dhcp-discover.c
  src/dnsmasq_interface.c
  src/events.c
  src/files.c
  src/log.c
  src/log.h
  src/setupVars.c
  src/shmem.c
  src/signals.c
  src/syscalls/accept.c
  src/syscalls/fopen.c
  src/syscalls/ftlallocate.c
  src/syscalls/pthread_mutex_lock.c
  src/syscalls/recv.c
  src/syscalls/recvfrom.c
  src/syscalls/select.c
  src/syscalls/sendto.c
  src/syscalls/vfprintf.c
  src/syscalls/write.c
  test/arch_test.sh
  test/dnsmasq.conf
  test/pdns/pdns.conf
  test/pdns/recursor.conf
Labels: internal

#1338 Add query type "Blocked (special domain)"
  src/database/query-table.c
  src/datastructure.c
  src/dnsmasq_interface.c
  src/enums.h
  src/gc.c
  test/test_suite.bats
Labels: Enhancement

#1342 Fix for theoretical one byte buffer overflow
  src/procps.c
Labels: Bugfix

#1343 Log reply forcing only in DEBUG_QUERIES mode
  src/dnsmasq_interface.c
Labels: Bugfix
