Repository pi-hole/FTL, pull requests merged in 2022-09, with the labels that each got.

#1419 Attach binaries to release from the correct path
  .github/workflows/build.yml
Labels: internal

#1425 Improve deep CNAME inspection
  src/dnsmasq/forward.c
  src/dnsmasq/rfc1035.c
  src/dnsmasq_interface.c
  src/dnsmasq_interface.h
  test/gravity.db.sql
  test/pdns/setup.sh
  test/test_suite.bats
Labels: Bugfix

#1415 Add warning about inaccessible adlists to message table (Pi-hole diagnosis)
  src/database/gravity-db.c
  src/database/gravity-db.h
  src/database/message-table.c
  src/database/message-table.h
  src/datastructure.c
  src/dnsmasq_interface.c
  src/enums.h
  test/gravity.db.sql
Labels: Discourse Feature Request, PR: Code Review Required

#1429 Update embedded dnsmasq to v2.87rc1
  CMakeLists.txt
  src/dnsmasq/cache.c
  src/dnsmasq/dbus.c
  src/dnsmasq/dhcp-common.c
  src/dnsmasq/dhcp-protocol.h
  src/dnsmasq/dhcp.c
  src/dnsmasq/dhcp6-protocol.h
  src/dnsmasq/dhcp6.c
  src/dnsmasq/dnsmasq.c
  src/dnsmasq/dnsmasq.h
  src/dnsmasq/dnssec.c
  src/dnsmasq/domain-match.c
  src/dnsmasq/domain.c
  src/dnsmasq/dump.c
  src/dnsmasq/forward.c
  src/dnsmasq/hash-questions.c
  src/dnsmasq/helper.c
  src/dnsmasq/lease.c
  src/dnsmasq/netlink.c
  src/dnsmasq/network.c
  src/dnsmasq/option.c
  src/dnsmasq/poll.c
  src/dnsmasq/radv.c
  src/dnsmasq/rfc1035.c
  src/dnsmasq/rfc2131.c
  src/dnsmasq/rfc3315.c
  src/dnsmasq/rrfilter.c
  src/dnsmasq/tftp.c
  src/dnsmasq/util.c
Labels: dnsmasq update

#1431 v5.18
  .github/workflows/build.yml
  CMakeLists.txt
  build.sh
  src/api/api.c
  src/database/gravity-db.c
  src/database/gravity-db.h
  src/database/message-table.c
  src/database/message-table.h
  src/database/query-table.c
  src/datastructure.c
  src/datastructure.h
  src/dnsmasq/cache.c
  src/dnsmasq/dbus.c
  src/dnsmasq/dhcp-common.c
  src/dnsmasq/dhcp-protocol.h
  src/dnsmasq/dhcp.c
  src/dnsmasq/dhcp6-protocol.h
  src/dnsmasq/dhcp6.c
  src/dnsmasq/dnsmasq.c
  src/dnsmasq/dnsmasq.h
  src/dnsmasq/dnssec.c
  src/dnsmasq/domain-match.c
  src/dnsmasq/domain.c
  src/dnsmasq/dump.c
  src/dnsmasq/forward.c
  src/dnsmasq/hash-questions.c
  src/dnsmasq/helper.c
  src/dnsmasq/lease.c
  src/dnsmasq/netlink.c
  src/dnsmasq/network.c
  src/dnsmasq/option.c
  src/dnsmasq/poll.c
  src/dnsmasq/radv.c
  src/dnsmasq/rfc1035.c
  src/dnsmasq/rfc2131.c
  src/dnsmasq/rfc3315.c
  src/dnsmasq/rrfilter.c
  src/dnsmasq/tftp.c
  src/dnsmasq/util.c
  src/dnsmasq_interface.c
  src/dnsmasq_interface.h
  src/enums.h
  src/regex.c
  src/regex_r.h
  src/shmem.c
  src/shmem.h
  test/gravity.db.sql
  test/pdns/setup.sh
  test/run.sh
  test/test_suite.bats
Labels: internal

#1437 Only log disk space warning when usage increased
  src/gc.c
Labels: Enhancement, PR: Approved

#1438 Fix handling of dnssec-retry queries.
  src/dnsmasq_interface.c
Labels: Bugfix, Bug:Discourse

#1440 Revert "Do not run built workflow on dependabot pushes and PRs"
  .github/workflows/build.yml
Labels: PR: Approval Required, internal

#1441 Separate dependabot branch names with a hypthen to work around the dir depth restriction in the build workflow
  .github/dependabot.yml
Labels: PR: Approved, internal

#1439 FTL v5.18.1
  .github/dependabot.yml
  .github/workflows/build.yml
  src/dnsmasq_interface.c
  src/gc.c
Labels: Release, internal

#1449 Update embedded dnsmasq to v2.87
  CMakeLists.txt
  src/dnsmasq/forward.c
Labels: dnsmasq update
