Repository pi-hole/FTL, pull requests merged in 2022-10, with the labels that each got.

#1450 Fix audit log
  src/api/api.c
  src/database/gravity-db.c
  test/test_suite.bats
Labels: Bugfix

#1452 Fix printed error message when binding fails
  src/api/socket.c
Labels: Bugfix

#1453 FTL v5.19
  .github/workflows/stale.yml
  CMakeLists.txt
  FTLtest.sh
  src/api/api.c
  src/api/socket.c
  src/api/socket.h
  src/config.c
  src/daemon.c
  src/database/gravity-db.c
  src/dnsmasq/forward.c
  test/run.sh
  test/test_suite.bats
Labels: Release, internal

#1458 Switch SSH deploy action
  .github/workflows/build.yml
Labels: internal
