Repository pi-hole/FTL, pull requests merged in 2022-11, with the labels that each got.

#1465 Fix compatibility with gcc 12.2.0
  src/api/api.c
  src/args.c
  src/args.h
  src/datastructure.c
  src/datastructure.h
Labels: Bugfix, External issue

#1464 Improve shared memory protection
  src/daemon.c
  src/dnsmasq_interface.c
  src/main.c
  src/shmem.c
  src/shmem.h
  test/test_suite.bats
Labels: Bugfix

#1466 Remove repo specific issue and pull request template
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: Approval Required

#1467 Update included crypto library (nettle)
  .github/workflows/build.yml
  src/args.c
  test/pihole-FTL.conf
Labels: Discourse Feature Request, Code maintanance

#1459 Update README.MD
  README.md
Labels: PR: Approval Required

#1470 Tests: Use dnssec.works instead of verteiltesysteme.net
  test/test_suite.bats
Labels: Bugfix, Tests

#1469 Update embedded dnsmasq to v2.88test3
  CMakeLists.txt
  src/database/query-table.c
  src/datastructure.c
  src/dnsmasq/cache.c
  src/dnsmasq/config.h
  src/dnsmasq/dbus.c
  src/dnsmasq/dnsmasq.c
  src/dnsmasq/dnsmasq.h
  src/dnsmasq/domain-match.c
  src/dnsmasq/forward.c
  src/dnsmasq/inotify.c
  src/dnsmasq/metrics.c
  src/dnsmasq/metrics.h
  src/dnsmasq/network.c
  src/dnsmasq/option.c
  src/dnsmasq/rfc1035.c
  src/dnsmasq/rfc2131.c
  src/dnsmasq/util.c
  src/dnsmasq_interface.c
  src/enums.h
  src/gc.c
Labels: dnsmasq update

#1472 Update CI to ftl-build:v1.23 containers
  .github/workflows/build.yml
  src/CMakeLists.txt
  src/FindDBus.cmake
  src/dnsmasq/config.h
  src/dnsmasq/dnsmasq.h
  test/arch_test.sh
  test/run.sh
  test/test_suite.bats
Labels: Code maintanance

#1473 Pi-hole FTL v5.19
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build.yml
  .github/workflows/codespell.yml
  .github/workflows/sync-back-to-dev.yml
  CMakeLists.txt
  README.md
  src/CMakeLists.txt
  src/FindDBus.cmake
  src/api/api.c
  src/args.c
  src/args.h
  src/daemon.c
  src/database/gravity-db.c
  src/database/query-table.c
  src/datastructure.c
  src/datastructure.h
  src/dnsmasq/cache.c
  src/dnsmasq/config.h
  src/dnsmasq/dbus.c
  src/dnsmasq/dnsmasq.c
  src/dnsmasq/dnsmasq.h
  src/dnsmasq/domain-match.c
  src/dnsmasq/forward.c
  src/dnsmasq/inotify.c
  src/dnsmasq/metrics.c
  src/dnsmasq/metrics.h
  src/dnsmasq/network.c
  src/dnsmasq/option.c
  src/dnsmasq/rfc1035.c
  src/dnsmasq/rfc2131.c
  src/dnsmasq/util.c
  src/dnsmasq_interface.c
  src/enums.h
  src/gc.c
  src/main.c
  src/shmem.c
  src/shmem.h
  test/arch_test.sh
  test/pihole-FTL.conf
  test/run.sh
  test/test_suite.bats
Labels: Release, internal

#1480 Always ensure FTL messages are unique
  src/database/message-table.c
Labels: Enhancement, PR: Approval Required

#1485 Fix shared memory crashes in TCP forks
  src/shmem.c
Labels: Enhancement, Bugfix

#1489 Increase SQLite3's cache size
  src/CMakeLists.txt
Labels: Enhancement, SQLite3

#1491 Update embedded dnsmasq to v2.88rc3
  CMakeLists.txt
  src/dnsmasq/dbus.c
  src/dnsmasq/dnsmasq.h
  src/dnsmasq/option.c
Labels: dnsmasq update

#1494 Update embedded dnsmasq to v2.88rc4
  CMakeLists.txt
  src/dnsmasq/dnssec.c
  src/dnsmasq/domain-match.c
  src/dnsmasq/option.c
Labels: dnsmasq update

#1492 Embedded lua scripts into FTL
  .gitignore
  build.sh
  src/CMakeLists.txt
  src/args.c
  src/lua/ftl_lua.c
  src/lua/ftl_lua.h
  src/lua/lua.c
  src/lua/scripts/CMakeLists.txt
  src/lua/scripts/inspect.lua
  src/lua/scripts/scripts.h
  test/run.sh
Labels: lua

#1495 Update embedded LUA to 5.4.4
  patch/lua.sh
  patch/lua/0001-add-pihole-library.patch
  patch/sqlite3.sh
  src/args.c
  src/lua/ftl_lua.h
  src/lua/lapi.c
  src/lua/lapi.h
  src/lua/lauxlib.c
  src/lua/lauxlib.h
  src/lua/lbaselib.c
  src/lua/lcode.c
  src/lua/lcorolib.c
  src/lua/ldblib.c
  src/lua/ldebug.c
  src/lua/ldebug.h
  src/lua/ldo.c
  src/lua/ldo.h
  src/lua/lfunc.c
  src/lua/lfunc.h
  src/lua/lgc.c
  src/lua/lgc.h
  src/lua/linit.c
  src/lua/liolib.c
  src/lua/llex.c
  src/lua/llimits.h
  src/lua/lmathlib.c
  src/lua/lmem.c
  src/lua/loadlib.c
  src/lua/lobject.c
  src/lua/lobject.h
  src/lua/lopcodes.h
  src/lua/loslib.c
  src/lua/lparser.c
  src/lua/lparser.h
  src/lua/lstate.c
  src/lua/lstate.h
  src/lua/lstring.c
  src/lua/lstring.h
  src/lua/lstrlib.c
  src/lua/ltable.c
  src/lua/ltable.h
  src/lua/ltablib.c
  src/lua/ltm.c
  src/lua/lua.c
  src/lua/lua.h
  src/lua/luac.c
  src/lua/luaconf.h
  src/lua/lualib.h
  src/lua/lutf8lib.c
  src/lua/lvm.c
  src/lua/lvm.h
Labels: lua

#1496 Update embedded dnsmasq to v2.88rc5
  CMakeLists.txt
  src/dnsmasq/cache.c
  src/dnsmasq/config.h
  src/dnsmasq/dnsmasq.h
  src/dnsmasq/domain-match.c
  src/dnsmasq/forward.c
  src/dnsmasq/option.c
  src/dnsmasq/rfc1035.c
Labels: dnsmasq update
