Repository pi-hole/FTL, pull requests merged in 2023-11, with the labels that each got.

#1716 Update Error Message Referring to "Adlist"
  src/database/message-table.c
Labels: Pi-hole v6.0

#1722 Remove traces of reboot and poweroff
  src/api/api.h
  src/api/docs/content/specs/action.yaml
  src/api/docs/content/specs/main.yaml
Labels: Pi-hole v6.0

#1725 Only use IPv6 in the webserver when available
  src/config/config.c
  src/daemon.c
  src/daemon.h
Labels: Pi-hole v6.0

#1724 API tests: Use /api/endpoints
  src/api/api.c
  src/api/docs/CMakeLists.txt
  src/api/docs/content/specs/clients.yaml
  src/api/docs/content/specs/docs.yaml
  src/api/docs/content/specs/info.yaml
  src/api/docs/content/specs/main.yaml
  src/api/docs/content/specs/network.yaml
  src/api/docs/docs.h
  test/api/checkAPI.py
  test/api/libs/openAPI.py
  test/api/libs/responseVerifyer.py
Labels: Documentation, API, Pi-hole v6.0

#1730 Use webserver.domain as "account" in the TOTP QR code
  src/api/2fa.c
Labels: API, Pi-hole v6.0

#1740 Suggest sudo for pihole-FTL --config changes
  src/capabilities.h
  src/config/cli.c
Labels: CLI, Pi-hole v6.0

#1742 Fix free() being used in the wrong page
  src/api/search.c
Labels: Bugfix, Pi-hole v6.0

#1743 NULL after free()
  src/FTL.h
  src/syscalls/free.c
  src/syscalls/syscalls.h
Labels: Code maintanance

#1732 Changing dns.hosts does not need a restart
  src/api/config.c
  src/config/config.c
  src/config/config.h
Labels: Pi-hole v6.0

#1736 Always return full overTime data
  src/api/history.c
  test/test_suite.bats
Labels: Bugfix, Pi-hole v6.0, Needs testing

#1745 Run codespell on push
  .github/workflows/codespell.yml
Labels: Code maintanance

#1744 Add X.509 parsing capabilities
  src/args.c
  src/database/message-table.c
  src/database/message-table.h
  src/enums.h
  src/webserver/http-common.c
  src/webserver/webserver.c
  src/webserver/x509.c
  src/webserver/x509.h
  test/test_suite.bats
Labels: Pi-hole v6.0

#1733 Make number of maximum concurrent API sessions adjustable
  src/api/2fa.c
  src/api/api.h
  src/api/auth.c
  src/api/auth.h
  src/api/docs/content/specs/auth.yaml
  src/api/docs/content/specs/config.yaml
  src/config/config.c
  src/config/config.h
  src/database/session-table.c
  src/database/session-table.h
  test/api/libs/responseVerifyer.py
  test/pihole.toml
Labels: API, Pi-hole v6.0

#1747 Create dynamic validity period when generating X.509 certificate
  src/webserver/x509.c
Labels: Pi-hole v6.0

#1735 Fix domain modification
  src/database/gravity-db.c
Labels: Bugfix, Pi-hole v6.0

#1734 Make inclusion of /etc/dnsmasq.d/*.conf files configurable
  src/api/docs/content/specs/config.yaml
  src/config/config.c
  src/config/config.h
  src/config/dnsmasq_config.c
  test/pihole.toml
Labels: Pi-hole v6.0

#1749 Add "requires restart" for config items where it is missing
  src/config/config.c
Labels: Bugfix

#1750 Fix hint of dns.cnameRecords
  src/config/config.c
Labels: Pi-hole v6.0

#1751 Improve readability of `dnsmasq.conf` by adding blank lines to group similar settings
  src/config/dnsmasq_config.c
Labels: Pi-hole v6.0

#1739 Move dhcp.domain -> dns.domain
  src/api/docs/content/specs/config.yaml
  src/config/config.c
  src/config/config.h
  src/config/dnsmasq_config.c
  src/config/toml_writer.c
  src/setupVars.c
  test/pihole.toml
Labels: API, Pi-hole v6.0

#1755 Remove additonal spaces in dnsmasq.conf
  src/config/dnsmasq_config.c
Labels: Pi-hole v6.0

#1754 Use hostsdir for custom.list to avoid cache flushing on changes
  src/api/config.c
  src/config/cli.c
  src/config/dnsmasq_config.c
  src/config/dnsmasq_config.h
Labels: Enhancement, Pi-hole v6.0

#1756 (Re-)Allow TLD blocking using ABP style
  src/tools/gravity-parseList.c
Labels: Bugfix, Pi-hole v6.0, Needs testing

#1727 Declare pihole.toml as UTF-8 document
  src/config/config.h
  src/config/toml_helper.c
  src/config/toml_writer.c
  src/daemon.c
  src/daemon.h
  src/dnsmasq/dnsmasq.c
  src/main.c
  test/api/libs/responseVerifyer.py
  test/pihole.toml
  test/test_suite.bats
Labels: Pi-hole v6.0

#1759 Prevent unconditional free on error reporting
  src/api/list.c
  src/webserver/http-common.c
Labels: Bugfix, Pi-hole v6.0

#1731 Improve DHCP handling
  src/api/config.c
  src/api/docs/content/specs/config.yaml
  src/config/cli.c
  src/config/config.c
  src/config/config.h
  src/config/dnsmasq_config.c
  src/config/toml_helper.c
  test/api/libs/responseVerifyer.py
  test/pihole.toml
Labels: Bugfix, API, Pi-hole v6.0

#1746 Do not rewrite config files if unchanged
  src/config/dnsmasq_config.c
  src/config/toml_helper.c
  src/config/toml_helper.h
  src/config/toml_reader.c
  src/config/toml_writer.c
  src/files.c
  src/files.h
  test/run.sh
  test/test_suite.bats
Labels: Pi-hole v6.0

#1763 Fix group comments
  src/database/gravity-db.c
Labels: Bugfix, Pi-hole v6.0

#1764 Set CivetWeb authentication_domain
  patch/civetweb.sh
  patch/civetweb/0001-Do-not-try-to-guess-server-hostname-in-Civetweb-when.patch
  src/config/config.c
  src/webserver/civetweb/civetweb.c
  src/webserver/webserver.c
Labels: Pi-hole v6.0

#1761 Validate domains before adding them to the database via /api/list
  src/api/docs/content/specs/domains.yaml
  src/api/list.c
  src/tools/gravity-parseList.c
  src/tools/gravity-parseList.h
Labels: Pi-hole v6.0

#1765 Switch from libidn to libidn2 to get IDNA2008 support
  .devcontainer/devcontainer.json
  .github/Dockerfile
  src/CMakeLists.txt
  src/api/list.c
  src/api/search.c
  src/args.c
  src/dnsmasq/config.h
  test/test_suite.bats
Labels: SECURITY, Pi-hole v6.0

#1767 Fix possible crash when importing legacy DHCP config
  src/FTL.h
  src/config/config.c
  src/config/config.h
  src/config/legacy_reader.c
  src/database/gravity-db.c
  src/setupVars.c
  src/syscalls/CMakeLists.txt
  src/syscalls/string.c
  src/syscalls/syscalls.h
  src/webserver/x509.c
Labels: Bugfix, Pi-hole v6.0

#1771 /api/client: Include hostnames of clients specified by MAC
  src/api/list.c
  src/database/network-table.c
  src/database/network-table.h
  src/database/sqlite3-ext.c
Labels: Pi-hole v6.0

#1774 Only log number of stored sessions not total number
  src/database/session-table.c
Labels: Pi-hole v6.0

#1775 Inotify: Watch for config file MOVED_TO
  src/config/inotify.c
  test/test_suite.bats
Labels: Bugfix, Pi-hole v6.0

#1772 Log successful processing of pihole.toml on startup
  src/config/config.c
  src/config/config.h
  src/main.c
Labels: Pi-hole v6.0

#1738 Try to restore broken pihole.toml from rotated files
  src/config/config.c
  src/config/toml_helper.c
  src/config/toml_helper.h
  src/config/toml_reader.c
  src/config/toml_reader.h
  src/config/toml_writer.c
  src/files.c
  src/files.h
  src/zip/teleporter.c
  test/pihole.toml
  test/test_suite.bats
Labels: Bugfix, Pi-hole v6.0

#1780 Include PID in /api/logs
  src/api/docs/content/specs/logs.yaml
  src/api/logs.c
Labels: Bugfix, Pi-hole v6.0

#1778 Only reload pihole.toml if changed
  src/args.c
  src/config/config.c
  src/config/toml_writer.c
  src/files.c
  src/files.h
  src/gc.c
  test/test_suite.bats
Labels: Pi-hole v6.0

#1781 API: Clients without queries should not be included
  src/api/stats.c
Labels: Bugfix, Pi-hole v6.0

#1789 Increase default value of webserver.session.timeout to 30 min
  src/config/config.c
Labels: Pi-hole v6.0

#1791 Minor config comment fix
  src/config/config.c
  test/pihole.toml
Labels: Pi-hole v6.0

#1790 Remove deprecated dhcp.domain setting
  src/api/docs/content/specs/config.yaml
  src/config/config.c
  src/config/config.h
  src/config/toml_writer.c
  test/pihole.toml
Labels: Pi-hole v6.0, Deprecation

#1782 Implement wildcard X.509 SAN/CN (subject) domain checking
  src/webserver/x509.c
Labels: Bugfix, Pi-hole v6.0

#1792 Fix link from message table to list table
  src/database/message-table.c
Labels: Pi-hole v6.0

#1788 Disable cache optimizer for any negative TTL
  src/config/config.c
  src/config/dnsmasq_config.c
Labels: Pi-hole v6.0

#1694 Recycle memory to reduce footprint
  src/FTL.h
  src/api/docs/content/specs/stats.yaml
  src/api/stats.c
  src/database/aliasclients.c
  src/database/gravity-db.c
  src/database/query-table.c
  src/datastructure.c
  src/datastructure.h
  src/dnsmasq_interface.c
  src/gc.c
  src/overTime.c
  src/resolve.c
  src/shmem.c
  src/shmem.h
Labels: Enhancement, Bugfix, Pi-hole v6.0

#1794 Add missing bits to the .gitignore file
  .gitignore
Labels: Code maintanance, Pi-hole v6.0

#1784 Escape invalid domains possibly containing control characters
  src/args.c
  src/tools/gravity-parseList.c
Labels: Bugfix, Pi-hole v6.0

#1795 Remove CH TXT privacylevel.pihole entry
  src/dnsmasq/cache.c
  src/dnsmasq/dnsmasq.h
  src/dnsmasq/option.c
  src/webserver/webserver.h
Labels: Pi-hole v6.0
