Repository pi-hole/FTL, pull requests merged in 2023-09, with the labels that each got.

#1630 Clear web session on external password change
  src/api/auth.c
  src/config/cli.c
  src/config/config.c
  src/gc.c
  src/signals.c
Labels: Bugfix

#1607 Provide regex ID for API
  src/api/docs/content/specs/queries.yaml
  src/api/queries.c
  src/database/common.c
  src/database/query-table.c
  src/database/query-table.h
  src/datastructure.h
  src/dnsmasq/rfc1035.c
  src/dnsmasq_interface.c
  test/test_suite.bats
Labels: Pi-hole v6.0

#1643 use tagged v2.0 version of ftl-build
  .github/Dockerfile
Labels: internal

#1579 Add antigravity (subscribed allowlists with wildcard support)
  src/api/docs/content/specs/lists.yaml
  src/api/list.c
  src/api/search.c
  src/args.c
  src/database/gravity-db.c
  src/database/gravity-db.h
  src/dnsmasq_interface.c
  src/enums.h
  src/tools/gravity-parseList.c
  src/tools/gravity-parseList.h
  test/gravity.db.sql
  test/pdns/setup.sh
  test/test_suite.bats
Labels: Discourse Feature Request

#1647 Improve web theme handling
  src/api/CMakeLists.txt
  src/api/theme.c
  src/api/theme.h
  src/config/config.c
  src/config/config.h
  src/datastructure.c
  src/datastructure.h
  src/enums.h
  src/lua/ftl_lua.c
Labels: Pi-hole v6.0
