Repository pi-hole/FTL, pull requests merged in 2023-08, with the labels that each got.

#1609 Tweaks for the webserver port
  src/api/docs/content/specs/config.yaml
  src/config/config.c
  src/config/legacy_reader.c
  test/api/checkAPI.py
  test/pihole.toml
  test/test_suite.bats
Labels: Pi-hole v6.0

#1570 Copy missing information from man pihole-FTL to pihole-FTL -h
  src/args.c
Labels: PR: Approved

#1613 Fix API config value interpretation warning
  src/api/config.c
Labels: Bugfix, Pi-hole v6.0

#1612 Embed missing file API specs file specs/action.yaml
  src/api/docs/docs.h
Labels: Bugfix, Pi-hole v6.0

#1615 Ensure (at least try to!) detach disk database on SQL issues
  src/api/queries.c
  src/database/common.c
  src/database/query-table.c
Labels: Pi-hole v6.0

#1616 Fix 404 for GET /api/info/sensors when hwmon isn't available
  src/api/info.c
Labels: Bugfix, Pi-hole v6.0

#1618 Always get max query ID from disk
  src/database/query-table.c
  src/database/query-table.h
  src/main.c
Labels: Bugfix, Pi-hole v6.0

#1622 Hard limit for searching the adlists is 10,000
  src/api/docs/content/specs/search.yaml
Labels: Pi-hole v6.0
