Repository pi-hole/FTL, pull requests merged in 2023-12, with the labels that each got.

#1785 Improve FTL's file comparsion algorithm
  src/files.c
Labels: Bugfix, Pi-hole v6.0

#1799 Never recycle alias-clients
  src/gc.c
Labels: Bugfix, Pi-hole v6.0

#1800 Add priority string in logs (if applicable)
  src/api/docs/content/specs/logs.yaml
  src/api/logs.c
  src/config/legacy_reader.c
  src/config/toml_reader.c
  src/dnsmasq_interface.c
  src/log.c
  src/log.h
Labels: API, Pi-hole v6.0

#1801 Fix extra logging feature
  src/config/dnsmasq_config.c
Labels: Bugfix, Pi-hole v6.0

#1805 Do not start webserver if webserver.port is empty
  src/config/config.c
  src/webserver/webserver.c
  test/pihole.toml
Labels: Pi-hole v6.0

#1804 Fix CPU utilization calculation on 32 bit systems
  src/api/docs/content/specs/info.yaml
  src/daemon.c
  src/daemon.h
  src/gc.c
Labels: Pi-hole v6.0

#1796 Add config option files.gravity_tmp
  src/CMakeLists.txt
  src/api/auth.c
  src/api/dns.c
  src/api/docs/content/specs/config.yaml
  src/api/history.c
  src/api/info.c
  src/api/stats.c
  src/config/CMakeLists.txt
  src/config/cli.c
  src/config/config.c
  src/config/config.h
  src/config/dnsmasq_config.c
  src/config/legacy_reader.c
  src/config/setupVars.c
  src/config/setupVars.h
  src/config/toml_reader.c
  src/dnsmasq_interface.c
  src/files.c
  src/main.c
  test/pihole.toml
Labels: Pi-hole v6.0

#1811 Use regex_id instead of regex.id for query log sorting
  src/api/queries.c
Labels: Pi-hole v6.0

#1816 Update node version to 20
  .github/workflows/openapi-validator.yml
Labels: Pi-hole v6.0

#1819 Add pihole-FTL sqlite3 -ni ...
  src/args.c
  test/sqliterc
  test/test_suite.bats
Labels: Pi-hole v6.0

#1777 Fix possible crash with high client activity
  src/database/network-table.c
Labels: Bugfix

#1821 A few (actually many) small changes
  src/CMakeLists.txt
  src/api/config.c
  src/api/network.c
  src/api/queries.c
  src/api/stats.c
  src/args.c
  src/config/cli.c
  src/config/config.c
  src/config/legacy_reader.c
  src/config/password.c
  src/config/setupVars.c
  src/database/gravity-db.c
  src/database/gravity-db.h
  src/database/network-table.c
  src/dnsmasq/cache.c
  src/dnsmasq_interface.c
  src/lua/CMakeLists.txt
  src/regex.c
  src/resolve.c
  src/syscalls/vfprintf.c
  src/tools/dhcp-discover.c
  src/tre-regex/CMakeLists.txt
  src/vector.c
  src/webserver/civetweb/CMakeLists.txt
  src/webserver/civetweb/mod_lua.inl
  src/webserver/webserver.c
  src/zip/gzip.c
  src/zip/miniz/miniz.c
  src/zip/teleporter.c
  test/gravity.db.sql
Labels: Code maintanance, Pi-hole v6.0

#1823 Add soc_thermal as CPU temperature sensor
  src/api/info.c
Labels: Pi-hole v6.0

#1808 Implement special domains whitelisting
  src/dnsmasq_interface.c
Labels: Discourse Feature Request, Documentation needed

#1807 Implement special domains allowing
  src/dnsmasq_interface.c
  test/gravity.db.sql
  test/test_suite.bats
Labels: Discourse Feature Request, Documentation needed, Pi-hole v6.0

#1786 Do not pin SID to a specific IP address
  src/api/auth.c
  src/api/docs/content/specs/auth.yaml
Labels: SECURITY, Pi-hole v6.0

#1810 Implement special POST :batchDelete callbacks
  src/api/api.c
  src/api/docs/content/specs/clients.yaml
  src/api/docs/content/specs/domains.yaml
  src/api/docs/content/specs/groups.yaml
  src/api/docs/content/specs/lists.yaml
  src/api/docs/content/specs/main.yaml
  src/api/list.c
  src/api/stats_database.c
  src/database/gravity-db.c
  src/database/gravity-db.h
  src/webserver/http-common.h
Labels: Discourse Feature Request, Pi-hole v6.0

#1843 Update cJSON
  src/webserver/cJSON/cJSON.c
  src/webserver/cJSON/cJSON.h
Labels: Code maintanance, Pi-hole v6.0

#1842 Do not overwrite errors on ROLLBACK
  src/database/gravity-db.c
Labels: Bugfix, Pi-hole v6.0
