Repository pi-hole/FTL, pull requests merged in 2023-05, with the labels that each got.

#1554 Update embedded Lua to 5.4.5
  patch/lua/0001-add-pihole-library.patch
  src/lua/lapi.c
  src/lua/lapi.h
  src/lua/lauxlib.c
  src/lua/lcode.c
  src/lua/lcorolib.c
  src/lua/ldebug.c
  src/lua/ldebug.h
  src/lua/ldo.c
  src/lua/ldo.h
  src/lua/ldump.c
  src/lua/lfunc.c
  src/lua/lfunc.h
  src/lua/lgc.c
  src/lua/lgc.h
  src/lua/llex.c
  src/lua/llimits.h
  src/lua/lmathlib.c
  src/lua/lmem.c
  src/lua/loadlib.c
  src/lua/lobject.c
  src/lua/lobject.h
  src/lua/lopcodes.h
  src/lua/loslib.c
  src/lua/lparser.c
  src/lua/lstate.c
  src/lua/lstate.h
  src/lua/lstrlib.c
  src/lua/ltable.c
  src/lua/ltable.h
  src/lua/ltablib.c
  src/lua/ltm.c
  src/lua/ltm.h
  src/lua/lua.c
  src/lua/lua.h
  src/lua/luac.c
  src/lua/luaconf.h
  src/lua/lundump.c
  src/lua/lutf8lib.c
  src/lua/lvm.c
  src/lua/lvm.h
Labels: lua

#1555 Fix shown upstream for internally generated DNSSEC-queries being wrong in certain configurations
  src/config.c
  src/dnsmasq/forward.c
  src/dnsmasq_interface.c
Labels: Bugfix

#1556 Do not log unrealistic disk usage (docker + macOS bug)
  src/gc.c
Labels: Bugfix, Not a Pi-hole bug

#1552 Trigger stale workflow on issue comments to remove stale label immediately
  .github/workflows/stale.yml
Labels: internal

#1558 Update embedded Lua to v5.4.6
  src/lua/lcorolib.c
  src/lua/lstate.c
  src/lua/lua.h
Labels: lua

#1557 Add local network scanning feature (ARP)
  src/CMakeLists.txt
  src/args.c
  src/capabilities.c
  src/capabilities.h
  src/syscalls/recvfrom.c
  src/syscalls/sendto.c
  src/tools/CMakeLists.txt
  src/tools/arp-scan.c
  src/tools/arp-scan.h
  src/tools/dhcp-discover.c
  src/tools/dhcp-discover.h
Labels: Enhancement

#1561 Add capabilities check for feature dhcp-discover
  src/tools/dhcp-discover.c
Labels: PR: Approval Required, Capabiltities

#1559 Add list parsing feature for gravity
  src/CMakeLists.txt
  src/args.c
  src/args.h
  src/gravity-tools.c
  src/gravity-tools.h
Labels: PR: Approval Required

#1562 Tweak dhcp-discover subcommand
  deploy.sh
  src/syscalls/sendto.c
  src/tools/arp-scan.c
  src/tools/dhcp-discover.c
Labels: Bugfix

#1565 Fix missing update of `adlist.date_updated`
  src/CMakeLists.txt
  src/args.c
  src/tools/CMakeLists.txt
  src/tools/gravity-parseList.c
  src/tools/gravity-parseList.h
Labels: Bugfix, Bug in development
