Repository pi-hole/FTL, pull requests merged in 2023-07, with the labels that each got.

#1583 Change generated elliptic curve from secp521r1 to secp384r1
  src/webserver/x509.c
Labels: Bugfix, Bug in development

#1581 Fix SQL used to update existing adlists via the API
  src/database/gravity-db.c
Labels: Bugfix, Bug in development

#1569 Do not try to remove stale label on PRs
  .github/workflows/stale.yml
Labels: internal

#1586 Fix the Stale workflow
  .github/workflows/stale.yml
Labels: internal

#1588 Add OpenAPI Authentication and Authorization details for the API
  src/api/docs/content/index.html
  src/api/docs/content/specs/auth.yaml
  src/api/docs/content/specs/dns.yaml
  src/api/docs/content/specs/main.yaml
Labels: Documentation

#1580 Update embedded dnsmasq
  src/dnsmasq/cache.c
  src/dnsmasq/dnssec.c
  src/dnsmasq/forward.c
  src/dnsmasq/rfc1035.c
  src/dnsmasq_interface.c
  test/dnsmasq_warnings
Labels: dnsmasq update

#1594 Fix OpenAPI documentation login
  src/api/auth.c
  src/api/docs/CMakeLists.txt
  src/api/docs/content/external/geraintluff-sha256.min.js
  src/api/docs/content/index.html
  src/api/docs/content/pi-hole.js
  src/api/docs/docs.h
Labels: Bugfix, Bug in development

#1599 Fix total number in Query Log
  src/api/queries.c
Labels: Pi-hole v6.0

#1603 Add support for TRUNCATED DNSSEC status (2)
  src/dnsmasq_interface.c
Labels: Pi-hole v6.0

#1604 Fix API parameter parsing on 32bit architectures
  src/api/docs/content/specs/search.yaml
  src/api/queries.c
  src/api/search.c
  src/webserver/http-common.c
  src/webserver/http-common.h
Labels: Pi-hole v6.0

#1605 Fix Query Log total number without filtering
  src/api/queries.c
Labels: Bugfix, Pi-hole v6.0

#1601 Slash the slash
  src/api/docs/content/specs/queries.yaml
  src/webserver/lua_web.c
  src/webserver/webserver.c
Labels: Bugfix, Pi-hole v6.0

#1610 Fix upgrade of the password hash
  src/config/password.c
Labels: Bugfix, Pi-hole v6.0
