Repository pi-hole/FTL, pull requests merged in 2023-01, with the labels that each got.

#1520 Remove gray color in help output
  src/args.c
Labels: PR: Approval Required

#1515 Add action to close stale PR
  .github/workflows/stale_pr.yml
Labels: internal

#1523 v5.20.1
  .github/workflows/build.yml
  .github/workflows/codespell.yml
  .github/workflows/merge-conflict.yml
  .github/workflows/stale.yml
  .github/workflows/sync-back-to-dev.yml
  src/args.c
  src/database/query-table.c
Labels: Release, internal
