Repository pi-hole/FTL, pull requests merged in 2024-08, with the labels that each got.

#2024 Fix port 65535 for virtual cache and blocklist upstreams
  src/api/stats.c
Labels: Bugfix, API, Pi-hole v6.0

#2022 Improve network table code
  src/database/aliasclients.c
  src/database/common.c
  src/database/common.h
  src/database/network-table.c
  src/database/query-table.c
  src/datastructure.c
  src/datastructure.h
  src/dnsmasq_interface.c
Labels: Bugfix, Code maintanance, Pi-hole v6.0

#2025 Improve pihole-FTL process concurrency
  src/daemon.c
  src/dnsmasq/util.c
  src/log.c
  src/main.c
  src/procps.c
  src/procps.h
  src/shmem.c
  src/shmem.h
  test/test_suite.bats
Labels: Code maintanance, Pi-hole v6.0

#2026 Add new GET /api/padd endpoint
  .github/.codespellignore
  src/api/CMakeLists.txt
  src/api/api.c
  src/api/api.h
  src/api/config.c
  src/api/dns.c
  src/api/docs/CMakeLists.txt
  src/api/docs/content/specs/main.yaml
  src/api/docs/content/specs/padd.yaml
  src/api/docs/docs.h
  src/api/info.c
  src/api/network.c
  src/api/padd.c
  src/api/queries.c
  src/api/stats.c
  src/datastructure.c
  src/datastructure.h
Labels: Pi-hole v6.0

#2027 Fix NTP synchronization on devices not knowing the NTP service type
  src/ntp/client.c
Labels: Bugfix, Pi-hole v6.0

#2032 Fix Top Clients table
  src/api/stats.c
Labels: Bugfix, API, Pi-hole v6.0

#2033 Update embedded CivetWeb server
  patch/civetweb.sh
  patch/civetweb/0001-Add-FTL-URI-rewriting-changes-to-CivetWeb.patch
  patch/civetweb/0001-Add-NO_DLOPEN-option-to-civetweb-s-LUA-routines.patch
  patch/civetweb/0001-Add-mbedTLS-debug-logging-hook.patch
  patch/civetweb/0001-Allow-extended-ASCII-characters-in-URIs.patch
  patch/civetweb/0001-Log-debug-messages-to-webserver.log-when-debug.webse.patch
  patch/civetweb/0001-Register-CSRF-token-in-conn-request_info.patch
  src/args.c
  src/webserver/civetweb/civetweb.c
  src/webserver/civetweb/civetweb.h
  src/webserver/civetweb/handle_form.inl
  src/webserver/civetweb/match.inl
  src/webserver/civetweb/mod_lua.inl
  src/webserver/civetweb/mod_mbedtls.inl
  src/webserver/civetweb/timer.inl
  src/webserver/webserver.c
Labels: Code maintanance, Pi-hole v6.0

#2036 Improve incomplete installations support
  src/config/config.c
  src/config/toml_helper.c
Labels: Pi-hole v6.0

#2037 Allow other FTL process inside docker
  src/procps.c
Labels: Bugfix, Pi-hole v6.0

#2043 Fix possible double-free and avoid memory leaking
  src/api/config.c
  src/config/cli.c
  src/config/config.c
  src/config/config.h
  src/config/legacy_reader.c
  src/config/password.c
  src/config/setupVars.c
  src/resolve.c
Labels: Bugfix, Pi-hole v6.0

#2030 Implement DNS caching for queries blocked upstream
  .github/.codespellignore
  src/api/docs/content/specs/config.yaml
  src/api/padd.c
  src/api/stats.c
  src/config/config.c
  src/config/config.h
  src/datastructure.c
  src/datastructure.h
  src/dnsmasq/forward.c
  src/dnsmasq/rfc1035.c
  src/dnsmasq_interface.c
  src/dnsmasq_interface.h
  src/enums.h
  src/gc.c
  src/shmem.c
  test/pdns/setup.sh
  test/pihole.toml
  test/test_suite.bats
Labels: Pi-hole v6.0

#2046 Use ftl-build:v2.7 builder for Actions
  .github/Dockerfile
Labels: Pi-hole v6.0, GHA
