Repository pi-hole/FTL, pull requests merged in 2024-09, with the labels that each got.

#2041 Restart FTL on change of webserver.api.cli_pw
  src/config/config.c
  src/config/password.c
Labels: Pi-hole v6.0

#2048 Add GET /api/stats/summary -> .gravity.last_update
  src/api/docs/content/specs/stats.yaml
  src/api/stats.c
  src/database/gravity-db.c
  src/database/gravity-db.h
Labels: API, Pi-hole v6.0

#2047 Fix CPU % calculation
  src/api/info.c
  src/gc.c
  src/webserver/webserver.c
Labels: Bugfix, Pi-hole v6.0

#2049 Remove appending ?target=... when redirecting to login page
  src/webserver/lua_web.c
Labels: API, Pi-hole v6.0

#2042 Make v5 -> v6 migration verbose
  src/api/history.c
  src/config/setupVars.c
Labels: Pi-hole v6.0

#2050 Remove development-v6 references from dependabot
  .github/dependabot.yml
Labels: internal

#2055 Migrate legacy files into /etc/pihole/migration_backup_v6
  src/config/config.c
  src/config/dnsmasq_config.c
  src/config/dnsmasq_config.h
  src/config/setupVars.c
Labels: Pi-hole v6.0

#2054 Add queries per second (QPS) metric
  src/FTL.h
  src/api/docs/content/specs/info.yaml
  src/api/docs/content/specs/stats.yaml
  src/api/info.c
  src/api/stats.c
  src/dnsmasq_interface.c
  src/shmem.c
  src/shmem.h
Labels: API, Pi-hole v6.0

#2059 Fix possible crash due to incorrect setupVars.conf import
  src/FTL.h
  src/config/password.c
  src/config/setupVars.c
  src/config/toml_helper.c
  src/signals.c
  src/syscalls/free.c
  src/syscalls/syscalls.h
  src/webserver/webserver.c
Labels: Bugfix, Pi-hole v6.0

#2057 Ensure v6 imports CNAME records when reading v5 archives
  src/api/action.c
  src/api/api.c
  src/api/config.c
  src/api/teleporter.c
  src/config/config.c
  src/config/setupVars.c
  src/daemon.c
  src/main.c
  src/ntp/client.c
  src/signals.c
  src/signals.h
  src/webserver/http-common.h
  src/zip/teleporter.c
  test/test_suite.bats
Labels: Pi-hole v6.0

#2061 Check and create v6 migration directory if not exists
  src/api/teleporter.c
  src/config/config.c
  src/config/config.h
  src/config/dnsmasq_config.h
  src/config/setupVars.c
Labels: Pi-hole v6.0

#2062 Improve EDNS handling
  src/api/config.c
  src/api/docs/content/specs/config.yaml
  src/api/docs/content/specs/stats.yaml
  src/api/queries.c
  src/config/cli.c
  src/config/config.c
  src/config/config.h
  src/config/env.c
  src/config/toml_helper.c
  src/database/query-table.c
  src/datastructure.c
  src/datastructure.h
  src/dnsmasq/forward.c
  src/dnsmasq_interface.c
  src/dnsmasq_interface.h
  src/edns0.c
  src/enums.h
  src/gc.c
  test/pdns/luadns.lua
  test/pdns/recursor.conf
  test/pdns/setup.sh
  test/pihole.toml
  test/test_suite.bats
Labels: Discourse Feature Request, Pi-hole v6.0

#2060 Fix gzip help text
  src/args.c
  src/args.h
Labels: Bugfix, Documentation, Pi-hole v6.0

#2064 Move debug message behind debug flag
  src/dnsmasq_interface.c
Labels: Debugging, Pi-hole v6.0

#2065 Fix various CodeQL complaints
  src/FTL.h
  src/api/teleporter.c
  src/config/legacy_reader.c
  src/database/sqlite3-ext.h
  src/dnsmasq_interface.c
  src/enums.h
  src/log.c
  src/ntp/client.c
  src/ntp/server.c
  src/overTime.c
  src/regex.c
  src/shmem.c
  src/timers.c
  src/tools/gravity-parseList.h
  src/tools/netlink.c
  src/webserver/webserver.c
  src/webserver/x509.c
  src/zip/gzip.c
  src/zip/teleporter.c
Labels: SECURITY, Pi-hole v6.0

#2070 Fix Civetweb Lua error reporting issue
  .devcontainer/devcontainer.json
  patch/lua.sh
  patch/lua/0001-Add-bundled-script-loading-into-luaL_openlibs-to-mak.patch
  patch/lua/0001-Increase-LUA_IDSIZE-so-that-long-script-filenames-as.patch
  src/lua/ftl_lua.h
  src/lua/linit.c
  src/lua/lua.c
  src/lua/luaconf.h
  src/webserver/civetweb/mod_lua.inl
  src/webserver/lua_web.c
  test/broken_lua.lp
  test/broken_lua_2.lp
  test/run.sh
  test/test_suite.bats
Labels: Bugfix, Pi-hole v6.0

#2071 Disentangle info/ftl database domain numbers
  src/api/docs/content/specs/info.yaml
  src/api/info.c
  src/database/gravity-db.c
  src/datastructure.c
  src/enums.h
  src/shmem.h
Labels: API, Pi-hole v6.0

#2074 Fix incorrect page count on some Query Log shortcuts
  src/api/queries.c
Labels: Bugfix, Pi-hole v6.0

#2073 Restart FTL to enforce flushing the cache when dns.piholePTR is changed
  src/config/config.c
  test/pihole.toml
Labels: Bugfix, Pi-hole v6.0
