Repository pi-hole/FTL, pull requests merged in 2024-01, with the labels that each got.

#1848 Simplify artifacts download
  .github/workflows/build.yml
Labels: Pi-hole v6.0

#1840 Implement DNS cache recycling
  src/database/query-table.c
  src/datastructure.c
  src/datastructure.h
  src/dnsmasq_interface.c
  src/gc.c
  src/log.c
Labels: Bugfix, Pi-hole v6.0

#1806 Use WAL, remove (and strip) SQLite3 shared-cache support and improve attached database handling
  src/CMakeLists.txt
  src/FTL.h
  src/api/info.c
  src/api/queries.c
  src/database/common.c
  src/database/database-thread.c
  src/database/message-table.c
  src/database/query-table.c
  src/database/query-table.h
  src/database/session-table.c
  src/dnsmasq_interface.c
  src/main.c
Labels: Code maintanance, Pi-hole v6.0

#1576 Group dependabot PRs
  .github/dependabot.yml
Labels: internal

#1766 Add support for legacy Teleporter archives
  .devcontainer/devcontainer.json
  src/api/list.c
  src/api/teleporter.c
  src/config/config.c
  src/config/config.h
  src/config/legacy_reader.c
  src/config/setupVars.c
  src/main.c
  src/zip/CMakeLists.txt
  src/zip/gzip.c
  src/zip/gzip.h
  src/zip/tar.c
  src/zip/tar.h
  src/zip/teleporter.c
  src/zip/teleporter.h
Labels: Discourse Feature Request, Pi-hole v6.0, Needs testing

#1822 Pi-hole FTL v5.24
  .github/dependabot.yml
  .github/workflows/build.yml
  .github/workflows/codespell.yml
  .github/workflows/stale.yml
  .github/workflows/stale_pr.yml
  .github/workflows/sync-back-to-dev.yml
  src/args.c
  src/database/network-table.c
  src/dnsmasq_interface.c
Labels: Release

#1835 Fix one-of definition in clients, domains, groups, and lists POST
  src/api/docs/content/specs/clients.yaml
  src/api/docs/content/specs/domains.yaml
  src/api/docs/content/specs/groups.yaml
  src/api/docs/content/specs/lists.yaml
Labels: API, Pi-hole v6.0

#1813 Only include as many domains as we have in the sorted array
  src/api/stats.c
Labels: Bugfix, Pi-hole v6.0

#1851 Add Location header for newly created groups/clients/domains/lists
  src/api/list.c
Labels: Pi-hole v6.0

#1728 Add authentication via query string
  src/api/auth.c
  test/api/libs/FTLAPI.py
Labels: API, Pi-hole v6.0

#1836 Fix DELETE API endpoints return codes
  src/api/auth.c
  src/api/config.c
  src/api/dhcp.c
  src/api/docs/content/specs/auth.yaml
  src/api/docs/content/specs/clients.yaml
  src/api/docs/content/specs/config.yaml
  src/api/docs/content/specs/dhcp.yaml
  src/api/docs/content/specs/domains.yaml
  src/api/docs/content/specs/groups.yaml
  src/api/docs/content/specs/info.yaml
  src/api/docs/content/specs/lists.yaml
  src/api/docs/content/specs/network.yaml
  src/api/info.c
  src/api/list.c
  src/api/network.c
  src/config/cli.c
  src/config/password.c
  src/config/password.h
  src/database/gravity-db.c
  src/database/gravity-db.h
  src/database/message-table.c
  src/database/message-table.h
  src/database/network-table.c
  src/database/network-table.h
  src/dnsmasq_interface.c
  src/webserver/json_macros.h
Labels: Bugfix, API, Pi-hole v6.0

#1839 If someone terminates FTL, try to obtain who is the murderer and log it
  src/dnsmasq/dnsmasq.c
  src/signals.c
  src/signals.h
Labels: Pi-hole v6.0

#1703 Managing DHCP leases is only possible when the DHCP server is enabled
  src/api/dhcp.c
  src/api/docs/content/specs/dhcp.yaml
  src/dnsmasq_interface.c
  src/dnsmasq_interface.h
Labels: API, Pi-hole v6.0

#1831 Update ftl-build container to v2.5
  .devcontainer/devcontainer.json
  .github/Dockerfile
Labels: Code maintanance, Pi-hole v6.0

#1752 Remove obsolet local.list
  src/config/dnsmasq_config.c
  src/dnsmasq_interface.c
Labels: Pi-hole v6.0

#1859 Return null as version in /api/info/version if not available
  src/api/docs/content/specs/info.yaml
  src/api/info.c
Labels: Pi-hole v6.0

#1832 Limit number of clients returned by /api/history/clients
  src/api/api.h
  src/api/docs/content/specs/config.yaml
  src/api/docs/content/specs/history.yaml
  src/api/history.c
  src/api/stats.c
  src/config/config.c
  src/config/config.h
  src/datastructure.c
  test/pihole.toml
Labels: Enhancement, Discourse Feature Request, API, Pi-hole v6.0

#1611 Add regex filtering support for domains on the Query Log
  src/api/api.h
  src/api/auth.c
  src/api/docs/content/specs/config.yaml
  src/api/history.c
  src/api/queries.c
  src/api/stats.c
  src/config/config.c
  src/config/setupVars.c
  test/pihole.toml
Labels: Discourse Feature Request, Pi-hole v6.0

#1860 X.509: Create and export CA certificate
  src/webserver/x509.c
  test/test.crt
  test/test.pem
  test/test_ca.crt
  test/test_suite.bats
Labels: API, Pi-hole v6.0

#1864 Amend description of expiration field in GET /dhcp/leases
  src/api/docs/content/specs/dhcp.yaml
Labels: Documentation, API, Pi-hole v6.0

#1826 Improve and fix host name resolution
  src/args.c
  src/config/config.c
  src/daemon.c
  src/daemon.h
  src/database/network-table.c
  src/dnsmasq_interface.c
  src/resolve.c
  src/resolve.h
  test/test_suite.bats
Labels: Bugfix, Pi-hole v6.0
