Repository pi-hole/FTL, pull requests merged in 2025-07, with the labels that each got.

#2543 Fix foreign fork PRs
  .github/workflows/build.yml
Labels: Bugfix

#2558 Convert pihole.toml to markdown and auto PR to docs repo
  .devcontainer/devcontainer.json
  .github/workflows/build.yml
  src/config/config.c
  src/config/toml_helper.c
  test/pihole.toml
  tools/pihole_toml_to_markdown.py
Labels: internal

#2554 Support IPv6 in the DHCP API
  src/api/dhcp.c
  src/dnsmasq_interface.c
Labels: Bugfix

#2545 Remove remaining traces of ARP flush
  src/api/action.c
  src/api/api.c
  src/api/api.h
  src/api/docs/content/specs/action.yaml
  src/api/docs/content/specs/main.yaml
Labels: API

#2584 Add colors to the --config output
  src/args.c
  src/args.h
  src/config/cli.c
Labels: CLI
