Repository pi-hole/FTL, pull requests merged in 2025-03, with the labels that each got.

#2300 Prevent crash on failure to source secure randomness
  src/config/password.c
  src/daemon.c
  src/main.c
  src/webserver/x509.c
  src/webserver/x509.h
Labels: Bugfix

#2312 Update embedded CivetWeb
  patch/civetweb/0001-Expose-bound-to-addresses-from-CivetWeb-to-the-front.patch
  src/webserver/civetweb/civetweb.c
  src/webserver/civetweb/civetweb.h
  src/webserver/webserver.c
Labels: dependencies

#2313 Avoid CivetWeb crash if no optional port could be bound
  src/webserver/civetweb/civetweb.c
  src/webserver/webserver.c
Labels: Bugfix, CivetWeb bug

#2314 Empty DHCP range is valid
  src/config/config.c
  src/config/dnsmasq_config.c
  src/config/dnsmasq_config.h
Labels: Bug:Discourse

#2310 Fix first-time IPv6 client name resolution
  src/resolve.c
Labels: Bugfix

#2311 Fix API_EXCLUDE_DOMAINS migration
  src/config/setupVars.c
Labels: Bugfix

#2309 Tweak misc.etc_dnsmasq_d help text and scope - only read *.conf files
  src/config/config.c
  src/config/dnsmasq_config.c
  test/pihole.toml
Labels: Enhancement

#2326 Increase niceness of CivetWeb threads
  patch/civetweb.sh
  patch/civetweb/0001-Increase-niceness-of-all-civetweb-threads-as-DNS-ope.patch
  src/webserver/civetweb/civetweb.c
Labels: API

#2308 Pi-hole FTL v6.0.4
  CMakeLists.txt
  patch/civetweb.sh
  patch/civetweb/0001-Expose-bound-to-addresses-from-CivetWeb-to-the-front.patch
  patch/civetweb/0001-Increase-niceness-of-all-civetweb-threads-as-DNS-ope.patch
  src/CMakeLists.txt
  src/config/config.c
  src/config/dnsmasq_config.c
  src/config/dnsmasq_config.h
  src/config/env.c
  src/config/password.c
  src/config/setupVars.c
  src/config/validator.c
  src/config/validator.h
  src/daemon.c
  src/dnsmasq/tftp.c
  src/main.c
  src/resolve.c
  src/webserver/civetweb/civetweb.c
  src/webserver/civetweb/civetweb.h
  src/webserver/webserver.c
  src/webserver/x509.c
  src/webserver/x509.h
  test/pihole.toml
  test/run.sh
  test/test_suite.bats
Labels: Release

#2297 Add total CPU % to /info/system endpoint
  src/api/docs/content/specs/info.yaml
  src/api/info.c
  src/api/padd.c
  src/daemon.c
  src/daemon.h
  src/procps.c
  src/procps.h
Labels: API

#2332 Ensure proper shutdown when crashing in a thread
  src/signals.c
Labels: Bugfix

#2351 Fix unlocking warning in /api/history/clients
  src/api/history.c
Labels: Bugfix

#2352 Increase restrictions on POST /api/teleporter
  src/api/teleporter.c
Labels: Bugfix

#2357 Use keep-alive
  src/webserver/webserver.c
Labels: Enhancement, API, performance

#2355 Change default file serving behavior **possibly breaking**
  src/api/docs/content/specs/config.yaml
  src/config/config.c
  src/config/config.h
  src/webserver/lua_web.c
  src/webserver/webserver.c
  test/pihole.toml
  test/test_suite.bats
Labels: SECURITY, Breaking change

#2345 Add new special permitted upstream filter for Query Log
  src/api/docs/content/specs/queries.yaml
  src/api/queries.c
  src/datastructure.c
  src/datastructure.h
Labels: API

#2360 Do not overwrite externally given MAKEFLAGS if set
  build.sh
Labels: CI

#2365 Default-off 0x20 encoding
  .gitignore
  CMakeLists.txt
  src/dnsmasq/dnsmasq.h
  src/dnsmasq/forward.c
  src/dnsmasq/option.c
Labels: dnsmasq update

#2353 Simplify overTime processing
  src/datastructure.c
  src/datastructure.h
  src/gc.c
  src/overTime.c
Labels: Bugfix

#2337 Tweak API documentation for /docs
  src/api/docs/content/specs/docs.yaml
Labels: Documentation, API

#2315 Add Discovery of Designated Resolvers special zone blocking
  src/api/docs/content/specs/config.yaml
  src/config/config.c
  src/config/config.h
  src/dnsmasq_interface.c
  test/pihole.toml
Labels: Discourse Feature Request

#2368 Do not update webserver.threads in-place
  src/config/toml_reader.c
  src/webserver/webserver.c
Labels: Bugfix

#2374 Update embedded dnsmasq to v2.91rc6
  CMakeLists.txt
  src/dnsmasq/forward.c
  src/dnsmasq/rfc1035.c
Labels: dnsmasq update

#2336 Also set Expires= property for deleted cookies
  src/CMakeLists.txt
  src/api/auth.h
Labels: API

#2379 Fix docs for lists batchDelete
  src/api/docs/content/specs/lists.yaml
Labels: Documentation, API

#2380 Update dnsmasq tag to 2.91
  CMakeLists.txt
Labels: dnsmasq update

#2319 Allow prefix multiplexing behind reverse proxy
  src/api/docs/content/specs/config.yaml
  src/config/config.c
  src/config/config.h
  src/lua/ftl_lua.c
  src/webserver/lua_web.c
  src/webserver/lua_web.h
  src/webserver/webserver.c
  src/webserver/webserver.h
  test/pihole.toml
Labels: API, Feature Request

#2394 Pi-hole FTL v6.1
  .github/workflows/codespell.yml
  .github/workflows/openapi-validator.yml
  .gitignore
  CMakeLists.txt
  README.md
  build.sh
  package-lock.json
  package.json
  src/CMakeLists.txt
  src/api/auth.h
  src/api/docs/content/specs/config.yaml
  src/api/docs/content/specs/docs.yaml
  src/api/docs/content/specs/info.yaml
  src/api/docs/content/specs/lists.yaml
  src/api/docs/content/specs/queries.yaml
  src/api/history.c
  src/api/info.c
  src/api/padd.c
  src/api/queries.c
  src/api/teleporter.c
  src/config/config.c
  src/config/config.h
  src/config/dnsmasq_config.c
  src/config/env.c
  src/config/toml_reader.c
  src/daemon.c
  src/daemon.h
  src/database/database-thread.c
  src/database/query-table.c
  src/database/query-table.h
  src/datastructure.c
  src/datastructure.h
  src/dnsmasq/dnsmasq.h
  src/dnsmasq/forward.c
  src/dnsmasq/option.c
  src/dnsmasq/rfc1035.c
  src/dnsmasq_interface.c
  src/files.c
  src/files.h
  src/gc.c
  src/lua/ftl_lua.c
  src/main.c
  src/ntp/client.c
  src/ntp/ntp.h
  src/ntp/server.c
  src/overTime.c
  src/procps.c
  src/procps.h
  src/signals.c
  src/webserver/json_macros.h
  src/webserver/lua_web.c
  src/webserver/lua_web.h
  src/webserver/webserver.c
  src/webserver/webserver.h
  test/pihole.toml
  test/test_suite.bats
Labels: Release, internal
